import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
const inter = Inter({ subsets: ["latin"] });
import {ClerkProvider, ClerkLoaded, ClerkLoading} from '@clerk/nextjs'
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
   
      <body className={inter.className}>
      <Navbar />
        <ClerkLoading>
            <div className="fixed top-0 left-0 h-screen w-screen flex justify-center items-center">
              <p className="text-gray-800 font-bold text-2xl">Loading...</p>
            </div>
        </ClerkLoading>
        <ClerkLoaded>
        {children}
        <Footer />
        </ClerkLoaded>
        </body>
    </html>
    </ClerkProvider>
  );
}
